	IMPORT IO_reset
	IMPORT Z80_IN
	IMPORT Z80_OUT
	IMPORT Z80_IN_C
	IMPORT Z80_OUT_C
	IMPORT thumbcall_r1
	IMPORT suspend
	IMPORT refreshEMUjoypads
	IMPORT vbaprint
	IMPORT serialinterrupt
	IMPORT VDPdata_W_ptr
	IMPORT BankSwitch0_W
	IMPORT BankSwitch1_W
	IMPORT BankSwitch2_W
	IMPORT BankSwitch3_W
	IMPORT PSLOT_W
	IMPORT Joystick_R
	IMPORT Joystick_W
	END
